version: '2'
services:
  web:
    build: ./docker/nginx
    ports:
      - 8888:443
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    command: npm start
    env_file: .env
    volumes:
      - .:/app
      - ../index.js:/app/strategy/index.js
      - ../lib:/app/strategy/lib
      - /app/node_modules
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:root@db/app
    links:
      - db
  db:
    image: mysql:5.6
    command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./docker/db/multibyte.cnf:/etc/mysql/conf.d/multibyte.cnf
      - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
